import { Element } from '../types';

const elements: Element[] = [
  {
    name: 'Hydrogen',
    symbol: 'H',
    atomicNumber: 1,
    atomicMass: 1.008,
    category: 'Nonmetal',
    electronConfiguration: '1',
    electronicConfiguration: '1s1',
    valenceElectrons: 1,
    oxidationStates: [-1, 1],
    group: 1,
    period: 1
  },
  {
    name: 'Helium',
    symbol: 'He',
    atomicNumber: 2,
    atomicMass: 4.003,
    category: 'Noble Gas',
    electronConfiguration: '2',
    electronicConfiguration: '1s2',
    valenceElectrons: 2,
    oxidationStates: [0],
    group: 18,
    period: 1
  },
  {
    name: 'Lithium',
    symbol: 'Li',
    atomicNumber: 3,
    atomicMass: 6.941,
    category: 'Alkali Metal',
    electronConfiguration: '2 1',
    electronicConfiguration: '[He] 2s1',
    valenceElectrons: 1,
    oxidationStates: [1],
    group: 1,
    period: 2
  },
  {
    name: 'Beryllium',
    symbol: 'Be',
    atomicNumber: 4,
    atomicMass: 9.012,
    category: 'Alkaline Earth Metal',
    electronConfiguration: '2 2',
    electronicConfiguration: '[He] 2s2',
    valenceElectrons: 2,
    oxidationStates: [2],
    group: 2,
    period: 2
  },
  {
    name: 'Boron',
    symbol: 'B',
    atomicNumber: 5,
    atomicMass: 10.811,
    category: 'Metalloid',
    electronConfiguration: '2 3',
    electronicConfiguration: '[He] 2s2 2p1',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 13,
    period: 2
  },
  {
    name: 'Carbon',
    symbol: 'C',
    atomicNumber: 6,
    atomicMass: 12.011,
    category: 'Nonmetal',
    electronConfiguration: '2 4',
    electronicConfiguration: '[He] 2s2 2p2',
    valenceElectrons: 4,
    oxidationStates: [-4, -3, -2, -1, 0, 1, 2, 3, 4],
    group: 14,
    period: 2
  },
  {
    name: 'Nitrogen',
    symbol: 'N',
    atomicNumber: 7,
    atomicMass: 14.007,
    category: 'Nonmetal',
    electronConfiguration: '2 5',
    electronicConfiguration: '[He] 2s2 2p3',
    valenceElectrons: 5,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5],
    group: 15,
    period: 2
  },
  {
    name: 'Oxygen',
    symbol: 'O',
    atomicNumber: 8,
    atomicMass: 15.999,
    category: 'Nonmetal',
    electronConfiguration: '2 6',
    electronicConfiguration: '[He] 2s2 2p4',
    valenceElectrons: 6,
    oxidationStates: [-2, -1, 1, 2],
    group: 16,
    period: 2
  },
  {
    name: 'Fluorine',
    symbol: 'F',
    atomicNumber: 9,
    atomicMass: 18.998,
    category: 'Halogen',
    electronConfiguration: '2 7',
    electronicConfiguration: '[He] 2s2 2p5',
    valenceElectrons: 7,
    oxidationStates: [-1],
    group: 17,
    period: 2
  },
  {
    name: 'Neon',
    symbol: 'Ne',
    atomicNumber: 10,
    atomicMass: 20.180,
    category: 'Noble Gas',
    electronConfiguration: '2 8',
    electronicConfiguration: '[He] 2s2 2p6',
    valenceElectrons: 8,
    oxidationStates: [0],
    group: 18,
    period: 2
  },
  {
    name: 'Sodium',
    symbol: 'Na',
    atomicNumber: 11,
    atomicMass: 22.990,
    category: 'Alkali Metal',
    electronConfiguration: '2 8 1',
    electronicConfiguration: '[Ne] 3s1',
    valenceElectrons: 1,
    oxidationStates: [1],
    group: 1,
    period: 3
  },
  {
    name: 'Magnesium',
    symbol: 'Mg',
    atomicNumber: 12,
    atomicMass: 24.305,
    category: 'Alkaline Earth Metal',
    electronConfiguration: '2 8 2',
    electronicConfiguration: '[Ne] 3s2',
    valenceElectrons: 2,
    oxidationStates: [2],
    group: 2,
    period: 3
  },
  {
    name: 'Aluminum',
    symbol: 'Al',
    atomicNumber: 13,
    atomicMass: 26.982,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 3',
    electronicConfiguration: '[Ne] 3s2 3p1',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 13,
    period: 3
  },
  {
    name: 'Silicon',
    symbol: 'Si',
    atomicNumber: 14,
    atomicMass: 28.086,
    category: 'Metalloid',
    electronConfiguration: '2 8 4',
    electronicConfiguration: '[Ne] 3s2 3p2',
    valenceElectrons: 4,
    oxidationStates: [-4, -3, -2, -1, 1, 2, 3, 4],
    group: 14,
    period: 3
  },
  {
    name: 'Phosphorus',
    symbol: 'P',
    atomicNumber: 15,
    atomicMass: 30.974,
    category: 'Nonmetal',
    electronConfiguration: '2 8 5',
    electronicConfiguration: '[Ne] 3s2 3p3',
    valenceElectrons: 5,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5],
    group: 15,
    period: 3
  },
  {
    name: 'Sulfur',
    symbol: 'S',
    atomicNumber: 16,
    atomicMass: 32.065,
    category: 'Nonmetal',
    electronConfiguration: '2 8 6',
    electronicConfiguration: '[Ne] 3s2 3p4',
    valenceElectrons: 6,
    oxidationStates: [-2, -1, 1, 2, 3, 4, 5, 6],
    group: 16,
    period: 3
  },
  {
    name: 'Chlorine',
    symbol: 'Cl',
    atomicNumber: 17,
    atomicMass: 35.453,
    category: 'Halogen',
    electronConfiguration: '2 8 7',
    electronicConfiguration: '[Ne] 3s2 3p5',
    valenceElectrons: 7,
    oxidationStates: [-1, 1, 3, 5, 7],
    group: 17,
    period: 3
  },
  {
    name: 'Argon',
    symbol: 'Ar',
    atomicNumber: 18,
    atomicMass: 39.948,
    category: 'Noble Gas',
    electronConfiguration: '2 8 8',
    electronicConfiguration: '[Ne] 3s2 3p6',
    valenceElectrons: 8,
    oxidationStates: [0],
    group: 18,
    period: 3
  },
  {
    name: 'Potassium',
    symbol: 'K',
    atomicNumber: 19,
    atomicMass: 39.098,
    category: 'Alkali Metal',
    electronConfiguration: '2 8 8 1',
    electronicConfiguration: '[Ar] 4s1',
    valenceElectrons: 1,
    oxidationStates: [1],
    group: 1,
    period: 4
  },
  {
    name: 'Calcium',
    symbol: 'Ca',
    atomicNumber: 20,
    atomicMass: 40.078,
    category: 'Alkaline Earth Metal',
    electronConfiguration: '2 8 8 2',
    electronicConfiguration: '[Ar] 4s2',
    valenceElectrons: 2,
    oxidationStates: [2],
    group: 2,
    period: 4
  },
  {
    name: 'Scandium',
    symbol: 'Sc',
    atomicNumber: 21,
    atomicMass: 44.956,
    category: 'Transition Metal',
    electronConfiguration: '2 8 9 2',
    electronicConfiguration: '[Ar] 3d1 4s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 4
  },
  {
    name: 'Titanium',
    symbol: 'Ti',
    atomicNumber: 22,
    atomicMass: 47.867,
    category: 'Transition Metal',
    electronConfiguration: '2 8 10 2',
    electronicConfiguration: '[Ar] 3d2 4s2',
    valenceElectrons: 4,
    oxidationStates: [-1, 2, 3, 4],
    group: 4,
    period: 4
  },
  {
    name: 'Vanadium',
    symbol: 'V',
    atomicNumber: 23,
    atomicMass: 50.942,
    category: 'Transition Metal',
    electronConfiguration: '2 8 11 2',
    electronicConfiguration: '[Ar] 3d3 4s2',
    valenceElectrons: 5,
    oxidationStates: [-1, 0, 1, 2, 3, 4, 5],
    group: 5,
    period: 4
  },
  {
    name: 'Chromium',
    symbol: 'Cr',
    atomicNumber: 24,
    atomicMass: 51.996,
    category: 'Transition Metal',
    electronConfiguration: '2 8 13 1',
    electronicConfiguration: '[Ar] 3d5 4s1',
    valenceElectrons: 6,
    oxidationStates: [-2, -1, 1, 2, 3, 4, 5, 6],
    group: 6,
    period: 4
  },
  {
    name: 'Manganese',
    symbol: 'Mn',
    atomicNumber: 25,
    atomicMass: 54.938,
    category: 'Transition Metal',
    electronConfiguration: '2 8 13 2',
    electronicConfiguration: '[Ar] 3d5 4s2',
    valenceElectrons: 7,
    oxidationStates: [-3, -2, -1, 1, 2, 3, 4, 5, 6, 7],
    group: 7,
    period: 4
  },
  {
    name: 'Iron',
    symbol: 'Fe',
    atomicNumber: 26,
    atomicMass: 55.845,
    category: 'Transition Metal',
    electronConfiguration: '2 8 14 2',
    electronicConfiguration: '[Ar] 3d6 4s2',
    valenceElectrons: 8,
    oxidationStates: [-2, -1, 1, 2, 3, 4, 5, 6],
    group: 8,
    period: 4
  },
  {
    name: 'Cobalt',
    symbol: 'Co',
    atomicNumber: 27,
    atomicMass: 58.933,
    category: 'Transition Metal',
    electronConfiguration: '2 8 15 2',
    electronicConfiguration: '[Ar] 3d7 4s2',
    valenceElectrons: 9,
    oxidationStates: [-1, 1, 2, 3, 4, 5],
    group: 9,
    period: 4
  },
  {
    name: 'Nickel',
    symbol: 'Ni',
    atomicNumber: 28,
    atomicMass: 58.693,
    category: 'Transition Metal',
    electronConfiguration: '2 8 16 2',
    electronicConfiguration: '[Ar] 3d8 4s2',
    valenceElectrons: 10,
    oxidationStates: [-1, 0, 1, 2, 3, 4],
    group: 10,
    period: 4
  },
  {
    name: 'Copper',
    symbol: 'Cu',
    atomicNumber: 29,
    atomicMass: 63.546,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 1',
    electronicConfiguration: '[Ar] 3d10 4s1',
    valenceElectrons: 11,
    oxidationStates: [1, 2, 3, 4],
    group: 11,
    period: 4
  },
  {
    name: 'Zinc',
    symbol: 'Zn',
    atomicNumber: 30,
    atomicMass: 65.38,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 2',
    electronicConfiguration: '[Ar] 3d10 4s2',
    valenceElectrons: 12,
    oxidationStates: [2],
    group: 12,
    period: 4
  },
  {
    name: 'Gallium',
    symbol: 'Ga',
    atomicNumber: 31,
    atomicMass: 69.723,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 18 3',
    electronicConfiguration: '[Ar] 3d10 4s2 4p1',
    valenceElectrons: 3,
    oxidationStates: [1, 2, 3],
    group: 13,
    period: 4
  },
  {
    name: 'Germanium',
    symbol: 'Ge',
    atomicNumber: 32,
    atomicMass: 72.630,
    category: 'Metalloid',
    electronConfiguration: '2 8 18 4',
    electronicConfiguration: '[Ar] 3d10 4s2 4p2',
    valenceElectrons: 4,
    oxidationStates: [-4, 1, 2, 3, 4],
    group: 14,
    period: 4
  },
  {
    name: 'Arsenic',
    symbol: 'As',
    atomicNumber: 33,
    atomicMass: 74.922,
    category: 'Metalloid',
    electronConfiguration: '2 8 18 5',
    electronicConfiguration: '[Ar] 3d10 4s2 4p3',
    valenceElectrons: 5,
    oxidationStates: [-3, 2, 3, 5],
    group: 15,
    period: 4
  },
  {
    name: 'Selenium',
    symbol: 'Se',
    atomicNumber: 34,
    atomicMass: 78.971,
    category: 'Nonmetal',
    electronConfiguration: '2 8 18 6',
    electronicConfiguration: '[Ar] 3d10 4s2 4p4',
    valenceElectrons: 6,
    oxidationStates: [-2, 2, 4, 6],
    group: 16,
    period: 4
  },
  {
    name: 'Bromine',
    symbol: 'Br',
    atomicNumber: 35,
    atomicMass: 79.904,
    category: 'Halogen',
    electronConfiguration: '2 8 18 7',
    electronicConfiguration: '[Ar] 3d10 4s2 4p5',
    valenceElectrons: 7,
    oxidationStates: [-1, 1, 3, 5],
    group: 17,
    period: 4
  },
  {
    name: 'Krypton',
    symbol: 'Kr',
    atomicNumber: 36,
    atomicMass: 83.798,
    category: 'Noble Gas',
    electronConfiguration: '2 8 18 8',
    electronicConfiguration: '[Ar] 3d10 4s2 4p6',
    valenceElectrons: 8,
    oxidationStates: [0, 2],
    group: 18,
    period: 4
  },
  {
    name: 'Rubidium',
    symbol: 'Rb',
    atomicNumber: 37,
    atomicMass: 85.468,
    category: 'Alkali Metal',
    electronConfiguration: '2 8 18 8 1',
    electronicConfiguration: '[Kr] 5s1',
    valenceElectrons: 1,
    oxidationStates: [1],
    group: 1,
    period: 5
  },
  {
    name: 'Strontium',
    symbol: 'Sr',
    atomicNumber: 38,
    atomicMass: 87.62,
    category: 'Alkaline Earth Metal',
    electronConfiguration: '2 8 18 8 2',
    electronicConfiguration: '[Kr] 5s2',
    valenceElectrons: 2,
    oxidationStates: [2],
    group: 2,
    period: 5
  },
  {
    name: 'Yttrium',
    symbol: 'Y',
    atomicNumber: 39,
    atomicMass: 88.906,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 9 2',
    electronicConfiguration: '[Kr] 4d1 5s2',
    valenceElectrons: 3,
    oxidationStates: [1, 2, 3],
    group: 3,
    period: 5
  },
  {
    name: 'Zirconium',
    symbol: 'Zr',
    atomicNumber: 40,
    atomicMass: 91.224,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 10 2',
    electronicConfiguration: '[Kr] 4d2 5s2',
    valenceElectrons: 4,
    oxidationStates: [-2, 1, 2, 3, 4],
    group: 4,
    period: 5
  },
  {
    name: 'Niobium',
    symbol: 'Nb',
    atomicNumber: 41,
    atomicMass: 92.906,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 12 1',
    electronicConfiguration: '[Kr] 4d4 5s1',
    valenceElectrons: 5,
    oxidationStates: [-1, 2, 3, 4, 5],
    group: 5,
    period: 5
  },
  {
    name: 'Molybdenum',
    symbol: 'Mo',
    atomicNumber: 42,
    atomicMass: 95.95,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 13 1',
    electronicConfiguration: '[Kr] 4d5 5s1',
    valenceElectrons: 6,
    oxidationStates: [-2, -1, 1, 2, 3, 4, 5, 6],
    group: 6,
    period: 5
  },
  {
    name: 'Technetium',
    symbol: 'Tc',
    atomicNumber: 43,
    atomicMass: 98,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 13 2',
    electronicConfiguration: '[Kr] 4d5 5s2',
    valenceElectrons: 7,
    oxidationStates: [-1, 1, 2, 3, 4, 5, 6, 7],
    group: 7,
    period: 5
  },
  {
    name: 'Ruthenium',
    symbol: 'Ru',
    atomicNumber: 44,
    atomicMass: 101.07,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 15 1',
    electronicConfiguration: '[Kr] 4d7 5s1',
    valenceElectrons: 8,
    oxidationStates: [-2, 1, 2, 3, 4, 5, 6, 7, 8],
    group: 8,
    period: 5
  },
  {
    name: 'Rhodium',
    symbol: 'Rh',
    atomicNumber: 45,
    atomicMass: 102.906,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 16 1',
    electronicConfiguration: '[Kr] 4d8 5s1',
    valenceElectrons: 9,
    oxidationStates: [-1, 1, 2, 3, 4, 5, 6],
    group: 9,
    period: 5
  },
  {
    name: 'Palladium',
    symbol: 'Pd',
    atomicNumber: 46,
    atomicMass: 106.42,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 18',
    electronicConfiguration: '[Kr] 4d10',
    valenceElectrons: 10,
    oxidationStates: [0, 2, 4],
    group: 10,
    period: 5
  },
   {
    name: 'Silver',
    symbol: 'Ag',
    atomicNumber: 47,
    atomicMass: 107.868,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 18 1',
    electronicConfiguration: '[Kr] 4d10 5s1',
    valenceElectrons: 11,
    oxidationStates: [1, 2, 3],
    group: 11,
    period: 5
  },
  {
    name: 'Cadmium',
    symbol: 'Cd',
    atomicNumber: 48,
    atomicMass: 112.414,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 18 2',
    electronicConfiguration: '[Kr] 4d10 5s2',
    valenceElectrons: 12,
    oxidationStates: [1, 2],
    group: 12,
    period: 5
  },
  {
    name: 'Indium',
    symbol: 'In',
    atomicNumber: 49,
    atomicMass: 114.818,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 18 18 3',
    electronicConfiguration: '[Kr] 4d10 5s2 5p1',
    valenceElectrons: 3,
    oxidationStates: [1, 2, 3],
    group: 13,
    period: 5
  },
  {
    name: 'Tin',
    symbol: 'Sn',
    atomicNumber: 50,
    atomicMass: 118.710,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 18 18 4',
    electronicConfiguration: '[Kr] 4d10 5s2 5p2',
    valenceElectrons: 4,
    oxidationStates: [-4, 2, 4],
    group: 14,
    period: 5
  },
  {
    name: 'Antimony',
    symbol: 'Sb',
    atomicNumber: 51,
    atomicMass: 121.760,
    category: 'Metalloid',
    electronConfiguration: '2 8 18 18 5',
    electronicConfiguration: '[Kr] 4d10 5s2 5p3',
    valenceElectrons: 5,
    oxidationStates: [-3, 3, 5],
    group: 15,
    period: 5
  },
  {
    name: 'Tellurium',
    symbol: 'Te',
    atomicNumber: 52,
    atomicMass: 127.60,
    category: 'Metalloid',
    electronConfiguration: '2 8 18 18 6',
    electronicConfiguration: '[Kr] 4d10 5s2 5p4',
    valenceElectrons: 6,
    oxidationStates: [-2, 2, 4, 5, 6],
    group: 16,
    period: 5
  },
  {
    name: 'Iodine',
    symbol: 'I',
    atomicNumber: 53,
    atomicMass: 126.904,
    category: 'Halogen',
    electronConfiguration: '2 8 18 18 7',
    electronicConfiguration: '[Kr] 4d10 5s2 5p5',
    valenceElectrons: 7,
    oxidationStates: [-1, 1, 3, 5, 7],
    group: 17,
    period: 5
  },
  {
    name: 'Xenon',
    symbol: 'Xe',
    atomicNumber: 54,
    atomicMass: 131.293,
    category: 'Noble Gas',
    electronConfiguration: '2 8 18 18 8',
    electronicConfiguration: '[Kr] 4d10 5s2 5p6',
    valenceElectrons: 8,
    oxidationStates: [0, 2, 4, 6, 8],
    group: 18,
    period: 5
  },
  {
    name: 'Caesium',
    symbol: 'Cs',
    atomicNumber: 55,
    atomicMass: 132.905,
    category: 'Alkali Metal',
    electronConfiguration: '2 8 18 18 8 1',
    electronicConfiguration: '[Xe] 6s1',
    valenceElectrons: 1,
    oxidationStates: [1],
    group: 1,
    period: 6
  },
  {
    name: 'Barium',
    symbol: 'Ba',
    atomicNumber: 56,
    atomicMass: 137.327,
    category: 'Alkaline Earth Metal',
    electronConfiguration: '2 8 18 18 8 2',
    electronicConfiguration: '[Xe] 6s2',
    valenceElectrons: 2,
    oxidationStates: [2],
    group: 2,
    period: 6
  },
  {
    name: 'Lanthanum',
    symbol: 'La',
    atomicNumber: 57,
    atomicMass: 138.905,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 18 9 2',
    electronicConfiguration: '[Xe] 5d1 6s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 6
  },
  {
    name: 'Cerium',
    symbol: 'Ce',
    atomicNumber: 58,
    atomicMass: 140.116,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 19 9 2',
    electronicConfiguration: '[Xe] 4f1 5d1 6s2',
    valenceElectrons: 4,
    oxidationStates: [2, 3, 4],
    group: 3,
    period: 6
  },
  {
    name: 'Praseodymium',
    symbol: 'Pr',
    atomicNumber: 59,
    atomicMass: 140.908,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 21 8 2',
    electronicConfiguration: '[Xe] 4f3 6s2',
    valenceElectrons: 3,
    oxidationStates: [2, 3, 4],
    group: 3,
    period: 6
  },
   {
    name: 'Neodymium',
    symbol: 'Nd',
    atomicNumber: 60,
    atomicMass: 144.242,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 22 8 2',
    electronicConfiguration: '[Xe] 4f4 6s2',
    valenceElectrons: 3,
    oxidationStates: [2, 3, 4],
    group: 3,
    period: 6
  },
  {
    name: 'Promethium',
    symbol: 'Pm',
    atomicNumber: 61,
    atomicMass: 145,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 23 8 2',
    electronicConfiguration: '[Xe] 4f5 6s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 6
  },
  {
    name: 'Samarium',
    symbol: 'Sm',
    atomicNumber: 62,
    atomicMass: 150.36,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 24 8 2',
    electronicConfiguration: '[Xe] 4f6 6s2',
    valenceElectrons: 3,
    oxidationStates: [2, 3],
    group: 3,
    period: 6
  },
  {
    name: 'Europium',
    symbol: 'Eu',
    atomicNumber: 63,
    atomicMass: 151.964,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 25 8 2',
    electronicConfiguration: '[Xe] 4f7 6s2',
    valenceElectrons: 3,
    oxidationStates: [2, 3],
    group: 3,
    period: 6
  },
  {
    name: 'Gadolinium',
    symbol: 'Gd',
    atomicNumber: 64,
    atomicMass: 157.25,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 25 9 2',
    electronicConfiguration: '[Xe] 4f7 5d1 6s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 6
  },
  {
    name: 'Terbium',
    symbol: 'Tb',
    atomicNumber: 65,
    atomicMass: 158.925,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 27 8 2',
    electronicConfiguration: '[Xe] 4f9 6s2',
    valenceElectrons: 3,
    oxidationStates: [3, 4],
    group: 3,
    period: 6
  },
  {
    name: 'Dysprosium',
    symbol: 'Dy',
    atomicNumber: 66,
    atomicMass: 162.500,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 28 8 2',
    electronicConfiguration: '[Xe] 4f10 6s2',
    valenceElectrons: 3,
    oxidationStates: [2, 3],
    group: 3,
    period: 6
  },
  {
    name: 'Holmium',
    symbol: 'Ho',
    atomicNumber: 67,
    atomicMass: 164.930,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 29 8 2',
    electronicConfiguration: '[Xe] 4f11 6s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 6
  },
  {
    name: 'Erbium',
    symbol: 'Er',
    atomicNumber: 68,
    atomicMass: 167.259,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 30 8 2',
    electronicConfiguration: '[Xe] 4f12 6s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 6
  },
  {
    name: 'Thulium',
    symbol: 'Tm',
    atomicNumber: 69,
    atomicMass: 168.934,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 31 8 2',
    electronicConfiguration: '[Xe] 4f13 6s2',
    valenceElectrons: 3,
    oxidationStates: [2, 3],
    group: 3,
    period: 6
  },
  {
    name: 'Ytterbium',
    symbol: 'Yb',
    atomicNumber: 70,
    atomicMass: 173.045,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 32 8 2',
    electronicConfiguration: '[Xe] 4f14 6s2',
    valenceElectrons: 3,
    oxidationStates: [2, 3],
    group: 3,
    period: 6
  },
  {
    name: 'Lutetium',
    symbol: 'Lu',
    atomicNumber: 71,
    atomicMass: 174.967,
    category: 'Lanthanide',
    electronConfiguration: '2 8 18 32 9 2',
    electronicConfiguration: '[Xe] 4f14 5d1 6s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 6
  },
  {
    name: 'Hafnium',
    symbol: 'Hf',
    atomicNumber: 72,
    atomicMass: 178.49,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 10 2',
    electronicConfiguration: '[Xe] 4f14 5d2 6s2',
    valenceElectrons: 4,
    oxidationStates: [2, 3, 4],
    group: 4,
    period: 6
  },
  {
    name: 'Tantalum',
    symbol: 'Ta',
    atomicNumber: 73,
    atomicMass: 180.948,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 11 2',
    electronicConfiguration: '[Xe] 4f14 5d3 6s2',
    valenceElectrons: 5,
    oxidationStates: [-1, 2, 3, 4, 5],
    group: 5,
    period: 6
  },
    {
    name: 'Tungsten',
    symbol: 'W',
    atomicNumber: 74,
    atomicMass: 183.84,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 12 2',
    electronicConfiguration: '[Xe] 4f14 5d4 6s2',
    valenceElectrons: 6,
    oxidationStates: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
    group: 6,
    period: 6
  },
  {
    name: 'Rhenium',
    symbol: 'Re',
    atomicNumber: 75,
    atomicMass: 186.207,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 13 2',
    electronicConfiguration: '[Xe] 4f14 5d5 6s2',
    valenceElectrons: 7,
    oxidationStates: [-3, -1, 1, 2, 3, 4, 5, 6, 7],
    group: 7,
    period: 6
  },
  {
    name: 'Osmium',
    symbol: 'Os',
    atomicNumber: 76,
    atomicMass: 190.23,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 14 2',
    electronicConfiguration: '[Xe] 4f14 5d6 6s2',
    valenceElectrons: 8,
    oxidationStates: [-2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8],
    group: 8,
    period: 6
  },
  {
    name: 'Iridium',
    symbol: 'Ir',
    atomicNumber: 77,
    atomicMass: 192.217,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 15 2',
    electronicConfiguration: '[Xe] 4f14 5d7 6s2',
    valenceElectrons: 9,
    oxidationStates: [-3, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8],
    group: 9,
    period: 6
  },
  {
    name: 'Platinum',
    symbol: 'Pt',
    atomicNumber: 78,
    atomicMass: 195.084,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 17 1',
    electronicConfiguration: '[Xe] 4f14 5d9 6s1',
    valenceElectrons: 10,
    oxidationStates: [-2, -1, 0, 1, 2, 3, 4, 5, 6],
    group: 10,
    period: 6
  },
  {
    name: 'Gold',
    symbol: 'Au',
    atomicNumber: 79,
    atomicMass: 196.967,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 18 1',
    electronicConfiguration: '[Xe] 4f14 5d10 6s1',
    valenceElectrons: 11,
    oxidationStates: [-1, 1, 2, 3, 5],
    group: 11,
    period: 6
  },
  {
    name: 'Mercury',
    symbol: 'Hg',
    atomicNumber: 80,
    atomicMass: 200.592,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 18 2',
    electronicConfiguration: '[Xe] 4f14 5d10 6s2',
    valenceElectrons: 12,
    oxidationStates: [1, 2],
    group: 12,
    period: 6
  },
  {
    name: 'Thallium',
    symbol: 'Tl',
    atomicNumber: 81,
    atomicMass: 204.38,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 18 32 18 3',
    electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p1',
    valenceElectrons: 3,
    oxidationStates: [1, 3],
    group: 13,
    period: 6
  },
  {
    name: 'Lead',
    symbol: 'Pb',
    atomicNumber: 82,
    atomicMass: 207.2,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 18 32 18 4',
    electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p2',
    valenceElectrons: 4,
    oxidationStates: [-4, 2, 4],
    group: 14,
    period: 6
  },
  {
    name: 'Bismuth',
    symbol: 'Bi',
    atomicNumber: 83,
    atomicMass: 208.980,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 18 32 18 5',
    electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p3',
    valenceElectrons: 5,
    oxidationStates: [-3, 3, 5],
    group: 15,
    period: 6
  },
  {
    name: 'Polonium',
    symbol: 'Po',
    atomicNumber: 84,
    atomicMass: 209,
    category: 'Post-Transition Metal',
    electronConfiguration: '2 8 18 32 18 6',
    electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p4',
    valenceElectrons: 6,
    oxidationStates: [-2, 2, 4, 6],
    group: 16,
    period: 6
  },
  {
    name: 'Astatine',
    symbol: 'At',
    atomicNumber: 85,
    atomicMass: 210,
    category: 'Halogen',
    electronConfiguration: '2 8 18 32 18 7',
    electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p5',
    valenceElectrons: 7,
    oxidationStates: [-1, 1, 3, 5, 7],
    group: 17,
    period: 6
  },
  {
    name: 'Radon',
    symbol: 'Rn',
    atomicNumber: 86,
    atomicMass: 222,
    category: 'Noble Gas',
    electronConfiguration: '2 8 18 32 18 8',
    electronicConfiguration: '[Xe] 4f14 5d10 6s2 6p6',
    valenceElectrons: 8,
    oxidationStates: [2],
    group: 18,
    period: 6
  },
  {
    name: 'Francium',
    symbol: 'Fr',
    atomicNumber: 87,
    atomicMass: 223,
    category: 'Alkali Metal',
    electronConfiguration: '2 8 18 32 18 8 1',
    electronicConfiguration: '[Rn] 7s1',
    valenceElectrons: 1,
    oxidationStates: [1],
    group: 1,
    period: 7
  },
  {
    name: 'Radium',
    symbol: 'Ra',
    atomicNumber: 88,
    atomicMass: 226,
    category: 'Alkaline Earth Metal',
    electronConfiguration: '2 8 18 32 18 8 2',
    electronicConfiguration: '[Rn] 7s2',
    valenceElectrons: 2,
    oxidationStates: [2],
    group: 2,
    period: 7
  },
   {
    name: 'Actinium',
    symbol: 'Ac',
    atomicNumber: 89,
    atomicMass: 227,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 18 9 2',
    electronicConfiguration: '[Rn] 6d1 7s2',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 7
  },
  {
    name: 'Thorium',
    symbol: 'Th',
    atomicNumber: 90,
    atomicMass: 232.038,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 18 10 2',
    electronicConfiguration: '[Rn] 6d2 7s2',
    valenceElectrons: 4,
    oxidationStates: [2, 3, 4],
    group: 3,
    period: 7
  },
  {
    name: 'Protactinium',
    symbol: 'Pa',
    atomicNumber: 91,
    atomicMass: 231.036,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 20 9 2',
    electronicConfiguration: '[Rn] 5f2 6d1 7s2',
    valenceElectrons: 5,
    oxidationStates: [3, 4, 5],
    group: 3,
    period: 7
  },
  {
    name: 'Uranium',
    symbol: 'U',
    atomicNumber: 92,
    atomicMass: 238.029,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 21 9 2',
    electronicConfiguration: '[Rn] 5f3 6d1 7s2',
    valenceElectrons: 6,
    oxidationStates: [3, 4, 5, 6],
    group: 3,
    period: 7
  },
  {
    name: 'Neptunium',
    symbol: 'Np',
    atomicNumber: 93,
    atomicMass: 237,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 22 9 2',
    electronicConfiguration: '[Rn] 5f4 6d1 7s2',
    valenceElectrons: 6,
    oxidationStates: [3, 4, 5, 6, 7],
    group: 3,
    period: 7
  },
  {
    name: 'Plutonium',
    symbol: 'Pu',
    atomicNumber: 94,
    atomicMass: 244,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 24 8 2',
    electronicConfiguration: '[Rn] 5f6 7s2',
    valenceElectrons: 6,
    oxidationStates: [3, 4, 5, 6, 7],
    group: 3,
    period: 7
  },
    {
    name: 'Americium',
    symbol: 'Am',
    atomicNumber: 95,
    atomicMass: 243,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 25 8 2',
    electronicConfiguration: '[Rn] 5f7 7s2',
    valenceElectrons: 6,
    oxidationStates: [3, 4, 5, 6],
    group: 3,
    period: 7
  },
  {
    name: 'Curium',
    symbol: 'Cm',
    atomicNumber: 96,
    atomicMass: 247,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 25 9 2',
    electronicConfiguration: '[Rn] 5f7 6d1 7s2',
    valenceElectrons: 6,
    oxidationStates: [3, 4],
    group: 3,
    period: 7
  },
  {
    name: 'Berkelium',
    symbol: 'Bk',
    atomicNumber: 97,
    atomicMass: 247,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 27 9 2',
    electronicConfiguration: '[Rn] 5f9 7s2',
    valenceElectrons: 6,
    oxidationStates: [3],
    group: 3,
    period: 7
  },
  {
    name: 'Californium',
    symbol: 'Cf',
    atomicNumber: 98,
    atomicMass: 251,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 28 9 2',
    electronicConfiguration: '[Rn] 5f10 7s2',
    valenceElectrons: 6,
    oxidationStates: [3],
    group: 3,
    period: 7
  },
  {
    name: 'Einsteinium',
    symbol: 'Es',
    atomicNumber: 99,
    atomicMass: 252,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 29 9 2',
    electronicConfiguration: '[Rn] 5f11 7s2',
    valenceElectrons: 6,
    oxidationStates: [3],
    group: 3,
    period: 7
  },
  {
    name: 'Fermium',
    symbol: 'Fm',
    atomicNumber: 100,
    atomicMass: 257,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 30 9 2',
    electronicConfiguration: '[Rn] 5f12 7s2',
    valenceElectrons: 6,
    oxidationStates: [2, 3],
    group: 3,
    period: 7
  },
  {
    name: 'Mendelevium',
    symbol: 'Md',
    atomicNumber: 101,
    atomicMass: 258,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 31 9 2',
    electronicConfiguration: '[Rn] 5f13 7s2',
    valenceElectrons: 6,
    oxidationStates: [2, 3],
    group: 3,
    period: 7
  },
  {
    name: 'Nobelium',
    symbol: 'No',
    atomicNumber: 102,
    atomicMass: 259,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 32 9 2',
    electronicConfiguration: '[Rn] 5f14 7s2',
    valenceElectrons: 6,
    oxidationStates: [2, 3, 4],
    group: 3,
    period: 7
  },
  {
    name: 'Lawrencium',
    symbol: 'Lr',
    atomicNumber: 103,
    atomicMass: 262,
    category: 'Actinide',
    electronConfiguration: '2 8 18 32 32 10 2',
    electronicConfiguration: '[Rn] 5f14 7s2 7p1',
    valenceElectrons: 3,
    oxidationStates: [3],
    group: 3,
    period: 7
  },
  {
    name: 'Rutherfordium',
    symbol: 'Rf',
    atomicNumber: 104,
    atomicMass: 267,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 11 2',
    electronicConfiguration: '[Rn] 6d2 7s2',
    valenceElectrons: 4,
    oxidationStates: [4],
    group: 4,
    period: 7
  },
  {
    name: 'Dubnium',
    symbol: 'Db',
    atomicNumber: 105,
    atomicMass: 268,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 12 2',
    electronicConfiguration: '[Rn] 6d3 7s2',
    valenceElectrons: 5,
    oxidationStates: [3, 4, 5],
    group: 5,
    period: 7
  },
  {
    name: 'Seaborgium',
    symbol: 'Sg',
    atomicNumber: 106,
    atomicMass: 271,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 13 2',
    electronicConfiguration: '[Rn] 6d4 7s2',
    valenceElectrons: 6,
    oxidationStates: [4, 5, 6],
    group: 6,
    period: 7
  },
  {
    name: 'Bohrium',
    symbol: 'Bh',
    atomicNumber: 107,
    atomicMass: 270,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 14 2',
    electronicConfiguration: '[Rn] 6d5 7s2',
    valenceElectrons: 6,
    oxidationStates: [3, 5, 6],
    group: 7,
    period: 7
  },
  {
    name: 'Hassium',
    symbol: 'Hs',
    atomicNumber: 108,
    atomicMass: 277,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 15 2',
    electronicConfiguration: '[Rn] 6d6 7s2',
    valenceElectrons: 6,
    oxidationStates: [4, 6],
    group: 8,
    period: 7
  },
  {
    name: 'Meitnerium',
    symbol: 'Mt',
    atomicNumber: 109,
    atomicMass: 276,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 16 2',
    electronicConfiguration: '[Rn] 6d7 7s2',
    valenceElectrons: 6,
    oxidationStates: [1, 3, 4],
    group: 9,
    period: 7
  },
  {
    name: 'Darmstadtium',
    symbol: 'Ds',
    atomicNumber: 110,
    atomicMass: 281,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 17 2',
    electronicConfiguration: '[Rn] 6d8 7s2',
    valenceElectrons: 6,
    oxidationStates: [4, 5, 6],
    group: 10,
    period: 7
  },
  {
    name: 'Roentgenium',
    symbol: 'Rg',
    atomicNumber: 111,
    atomicMass: 282,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 18 2',
    electronicConfiguration: '[Rn] 6d9 7s2',
    valenceElectrons: 6,
    oxidationStates: [1, 3, 5],
    group: 11,
    period: 7
  },
  {
    name: 'Copernicium',
    symbol: 'Cn',
    atomicNumber: 112,
    atomicMass: 285,
    category: 'Transition Metal',
    electronConfiguration: '2 8 18 32 32 18 3',
    electronicConfiguration: '[Rn] 6d10 7s2',
    valenceElectrons: 6,
    oxidationStates: [0, 1, 2],
    group: 12,
    period: 7
  },
  {
    name: 'Nihonium',
    symbol: 'Nh',
    atomicNumber: 113,
    atomicMass: 286,
    category: 'Post-transition Metal',
    electronConfiguration: '2 8 18 32 32 18 4',
    electronicConfiguration: '[Rn] 7s2 7p1',
    valenceElectrons: 3,
    oxidationStates: [1, 3],
    group: 13,
    period: 7
  },
  {
    name: 'Flerovium',
    symbol: 'Fl',
    atomicNumber: 114,
    atomicMass: 289,
    category: 'Post-transition Metal',
    electronConfiguration: '2 8 18 32 32 18 5',
    electronicConfiguration: '[Rn] 7s2 7p2',
    valenceElectrons: 4,
    oxidationStates: [2, 4],
    group: 14,
    period: 7
  },
  {
    name: 'Moscovium',
    symbol: 'Mc',
    atomicNumber: 115,
    atomicMass: 288,
    category: 'Post-transition Metal',
    electronConfiguration: '2 8 18 32 32 18 6',
    electronicConfiguration: '[Rn] 7s2 7p3',
    valenceElectrons: 5,
    oxidationStates: [3, 5],
    group: 15,
    period: 7
  },
  {
    name: 'Livermorium',
    symbol: 'Lv',
    atomicNumber: 116,
    atomicMass: 293,
    category: 'Post-transition Metal',
    electronConfiguration: '2 8 18 32 32 18 7',
    electronicConfiguration: '[Rn] 7s2 7p4',
    valenceElectrons: 6,
    oxidationStates: [2, 4],
    group: 16,
    period: 7
  },
  {
    name: 'Tennessine',
    symbol: 'Ts',
    atomicNumber: 117,
    atomicMass: 294,
    category: 'Halogen',
    electronConfiguration: '2 8 18 32 32 18 8',
    electronicConfiguration: '[Rn] 7s2 7p5',
    valenceElectrons: 7,
    oxidationStates: [-1, 1, 3, 5, 7],
    group: 17,
    period: 7
  },
  {
    name: 'Oganesson',
    symbol: 'Og',
    atomicNumber: 118,
    atomicMass: 294,
    category: 'Noble Gas',
    electronConfiguration: '2 8 18 32 32 18 8',
    electronicConfiguration: '[Rn] 5f14 6d10 7s2 7p6',
    valenceElectrons: 8,
    oxidationStates: [0, 2, 4],
    group: 18,
    period: 7
  }
];

export const getElementByAtomicNumber = (atomicNumber: number): Element | null => {
  return elements.find(element => element.atomicNumber === atomicNumber) || null;
};

export const getElementBySymbol = (symbol: string): Element | null => {
  return elements.find(element => element.symbol.toLowerCase() === symbol.toLowerCase()) || null;
};

export const getElementByName = (name: string): Element | null => {
  return elements.find(element => element.name.toLowerCase() === name.toLowerCase()) || null;
};